import { useCallback, useEffect, useState, type FormEvent } from "react";

import { workspaceApi } from "../../services/workspace-api";
import type { ITicket, ITicketDraft, IWorkspace } from "../../types/workspace";
import { formatWorkspaceLabel } from "../../utils/workspace-presentation";
import { TICKET_PRIORITIES, TICKET_STATUSES } from "../../utils/workspace-validation";
import { workspaceDashboardClassNames } from "./workspace-dashboard.styles";

interface IWorkspaceDashboardPageProps { accessToken: string; workspaceId: string; onBack: () => void }
const emptyDraft: ITicketDraft = { title: "", status: "BACKLOG" };
const errorText = (error: unknown) => error instanceof Error ? error.message : "Something went wrong. Please try again.";

export function WorkspaceDashboardPage({ accessToken, workspaceId, onBack }: IWorkspaceDashboardPageProps) {
  const [workspace, setWorkspace] = useState<IWorkspace>(); const [tickets, setTickets] = useState<ITicket[]>(); const [error, setError] = useState<string>(); const [draft, setDraft] = useState<ITicket | ITicketDraft>();
  const canManageTickets = workspace?.role === "ADMIN";
  const load = useCallback(async () => { setError(undefined); try { const [currentWorkspace, currentTickets] = await Promise.all([workspaceApi.get(accessToken, workspaceId), workspaceApi.tickets(accessToken, workspaceId)]); setWorkspace(currentWorkspace); setTickets(currentTickets); } catch (cause) { setError(errorText(cause)); } }, [accessToken, workspaceId]);
  useEffect(() => { void load(); }, [load]);
  async function deleteTicket(ticket: ITicket) { if (!window.confirm(`Are you sure you want to delete “${ticket.title}”?`)) return; try { await workspaceApi.deleteTicket(accessToken, ticket.id); await load(); } catch (cause) { setError(errorText(cause)); } }
  if (error) return <section className={workspaceDashboardClassNames.page}><p className="workspace-page__eyebrow">Workspace</p><h1>Workspace unavailable</h1><p className={workspaceDashboardClassNames.error} role="alert">{error}</p><button className="workspace-secondary-action" onClick={onBack}>Back to workspaces</button></section>;
  if (!workspace || !tickets) return <section className={workspaceDashboardClassNames.page} aria-live="polite"><p className="workspace-page__eyebrow">Workspace</p><h1>Loading workspace…</h1><div className="workspace-loading" aria-label="Loading workspace"><span /><span /><span /></div></section>;
  return <section className={workspaceDashboardClassNames.page} aria-labelledby="workspace-heading"><header className="workspace-page__header workspace-dashboard__header"><div><button className="workspace-back-action" onClick={onBack}>← Back to workspaces</button><p className="workspace-page__eyebrow">Workspace overview</p><h1 id="workspace-heading">{workspace.name}</h1><p className="workspace-page__subtitle">{tickets.length} {tickets.length === 1 ? "ticket" : "tickets"} in this workspace</p></div>{canManageTickets && <button className="workspace-primary-action" onClick={() => setDraft(emptyDraft)}>Create ticket</button>}</header>{tickets.length === 0 ? <section className="workspace-empty"><h2>No tickets yet</h2><p>This workspace is ready for its first piece of work.</p>{canManageTickets && <button className="workspace-primary-action" onClick={() => setDraft(emptyDraft)}>Create the first ticket</button>}</section> : <div className="workspace-grid workspace-ticket-grid">{tickets.map((ticket) => <article className={`${workspaceDashboardClassNames.ticket} workspace-ticket-card`} key={ticket.id}><div className="workspace-ticket-card__meta"><span className="ticket-status">{formatWorkspaceLabel(ticket.status)}</span><span className="ticket-priority">{formatWorkspaceLabel(ticket.priority, "No priority")}</span></div><h2>{ticket.title}</h2>{ticket.description && <p className="workspace-ticket-card__description">{ticket.description}</p>}<dl className="workspace-ticket-card__details"><div><dt>Assignee</dt><dd>{ticket.assignee?.name ?? ticket.assignee?.email ?? "Unassigned"}</dd></div><div><dt>Last updated</dt><dd>{new Date(ticket.updatedAt).toLocaleString()}</dd></div></dl>{canManageTickets && <div className="workspace-card__actions"><button className="workspace-secondary-action" onClick={() => setDraft(ticket)}>Edit</button><button className="workspace-delete-action" onClick={() => void deleteTicket(ticket)}>Delete</button></div>}</article>)}</div>}{draft && <TicketDialog ticket={isExistingTicket(draft) ? draft : undefined} initialDraft={draft} onClose={() => setDraft(undefined)} onSubmit={async (next) => { if (isExistingTicket(draft)) await workspaceApi.updateTicket(accessToken, draft.id, next); else await workspaceApi.createTicket(accessToken, workspaceId, next); await load(); setDraft(undefined); }} />}</section>;
}

function isExistingTicket(draft: ITicket | ITicketDraft): draft is ITicket { return "id" in draft; }
function TicketDialog({ ticket, initialDraft, onClose, onSubmit }: { ticket?: ITicket; initialDraft: ITicketDraft; onClose: () => void; onSubmit: (draft: ITicketDraft) => Promise<void> }) { const [draft, setDraft] = useState<ITicketDraft>(initialDraft); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>(); async function submit(event: FormEvent) { event.preventDefault(); if (!draft.title.trim()) return setError("Ticket title is required."); setSaving(true); setError(undefined); try { await onSubmit({ ...draft, title: draft.title.trim() }); } catch (cause) { setError(errorText(cause)); setSaving(false); } } return <dialog open className={workspaceDashboardClassNames.dialog} aria-label={ticket ? "Edit ticket" : "Create ticket"}><form onSubmit={(event) => void submit(event)}><h2>{ticket ? "Edit ticket" : "Create ticket"}</h2>{error && <p role="alert">{error}</p>}<label>Title<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} disabled={saving} /></label><label>Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as ITicketDraft["status"] })} disabled={saving}>{TICKET_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label>Priority<select value={draft.priority ?? ""} onChange={(event) => setDraft({ ...draft, priority: event.target.value === "" ? undefined : event.target.value as ITicketDraft["priority"] })} disabled={saving}><option value="">Not set</option>{TICKET_PRIORITIES.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label>Description<textarea value={draft.description ?? ""} onChange={(event) => setDraft({ ...draft, description: event.target.value || undefined })} disabled={saving} /></label><label>Assignee ID<input value={draft.assigneeId ?? ""} onChange={(event) => setDraft({ ...draft, assigneeId: event.target.value || undefined })} disabled={saving} /></label><button disabled={saving}>{saving ? "Saving…" : "Save ticket"}</button><button type="button" disabled={saving} onClick={onClose}>Cancel</button></form></dialog>; }
