import { useCallback, useEffect, useState, type FormEvent } from "react";

import { workspaceApi } from "../../services/workspace-api";
import type { ITicket, ITicketDraft, IWorkspace } from "../../types/workspace";
import { TICKET_PRIORITIES, TICKET_STATUSES } from "../../utils/workspace-validation";
import { workspaceDashboardClassNames } from "./workspace-dashboard.styles";

interface IWorkspaceDashboardPageProps { accessToken: string; workspaceId: string; onBack: () => void; canManageTickets?: boolean }
const emptyDraft: ITicketDraft = { title: "", status: "BACKLOG" };
const errorText = (error: unknown) => error instanceof Error ? error.message : "Something went wrong. Please try again.";

export function WorkspaceDashboardPage({ accessToken, workspaceId, onBack, canManageTickets = true }: IWorkspaceDashboardPageProps) {
  const [workspace, setWorkspace] = useState<IWorkspace>(); const [tickets, setTickets] = useState<ITicket[]>(); const [error, setError] = useState<string>(); const [draft, setDraft] = useState<ITicket | ITicketDraft>();
  const load = useCallback(async () => { setError(undefined); try { const [currentWorkspace, currentTickets] = await Promise.all([workspaceApi.get(accessToken, workspaceId), workspaceApi.tickets(accessToken, workspaceId)]); setWorkspace(currentWorkspace); setTickets(currentTickets); } catch (cause) { setError(errorText(cause)); } }, [accessToken, workspaceId]);
  useEffect(() => { void load(); }, [load]);
  async function deleteTicket(ticket: ITicket) { if (!window.confirm(`Are you sure you want to delete “${ticket.title}”?`)) return; try { await workspaceApi.deleteTicket(accessToken, ticket.id); await load(); } catch (cause) { setError(errorText(cause)); } }
  if (error) return <section className={workspaceDashboardClassNames.page}><h1>Workspace unavailable</h1><p className={workspaceDashboardClassNames.error} role="alert">{error}</p><button onClick={onBack}>Back to workspaces</button></section>;
  if (!workspace || !tickets) return <section className={workspaceDashboardClassNames.page} aria-live="polite"><h1>Loading workspace…</h1><p>Loading tickets…</p></section>;
  return <section className={workspaceDashboardClassNames.page} aria-labelledby="workspace-heading"><header><div><button onClick={onBack}>Back to workspaces</button><h1 id="workspace-heading">{workspace.name}</h1></div>{canManageTickets && <button onClick={() => setDraft(emptyDraft)}>Create Ticket</button>}</header>{tickets.length === 0 && <p>No tickets exist yet.{canManageTickets ? " Create the first ticket to get started." : ""}</p>}<div className="workspace-grid">{tickets.map((ticket) => <article className={workspaceDashboardClassNames.ticket} key={ticket.id}><h2>{ticket.title}</h2><p>Status: {ticket.status.replaceAll("_", " ")}</p><p>Priority: {ticket.priority?.replaceAll("_", " ") ?? "Not set"}</p>{ticket.description && <p>{ticket.description}</p>}<p>Assignee: {ticket.assignee?.name ?? ticket.assignee?.email ?? "Unassigned"}</p><p>Updated: {new Date(ticket.updatedAt).toLocaleString()}</p>{canManageTickets && <><button onClick={() => setDraft(ticket)}>Edit</button><button onClick={() => void deleteTicket(ticket)}>Delete</button></>}</article>)}</div>{draft && <TicketDialog ticket={isExistingTicket(draft) ? draft : undefined} initialDraft={draft} onClose={() => setDraft(undefined)} onSubmit={async (next) => { if (isExistingTicket(draft)) await workspaceApi.updateTicket(accessToken, draft.id, next); else await workspaceApi.createTicket(accessToken, workspaceId, next); await load(); setDraft(undefined); }} />}</section>;
}

function isExistingTicket(draft: ITicket | ITicketDraft): draft is ITicket { return "id" in draft; }

function TicketDialog({ ticket, initialDraft, onClose, onSubmit }: { ticket?: ITicket; initialDraft: ITicketDraft; onClose: () => void; onSubmit: (draft: ITicketDraft) => Promise<void> }) {
  const [draft, setDraft] = useState<ITicketDraft>(initialDraft); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: FormEvent) { event.preventDefault(); if (!draft.title.trim()) return setError("Ticket title is required."); setSaving(true); setError(undefined); try { await onSubmit({ ...draft, title: draft.title.trim() }); } catch (cause) { setError(errorText(cause)); setSaving(false); } }
  return <dialog open className={workspaceDashboardClassNames.dialog} aria-label={ticket ? "Edit ticket" : "Create ticket"}><form onSubmit={(event) => void submit(event)}><h2>{ticket ? "Edit ticket" : "Create ticket"}</h2>{error && <p role="alert">{error}</p>}<label>Title<input autoFocus value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} disabled={saving} /></label><label>Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as ITicketDraft["status"] })} disabled={saving}>{TICKET_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label>Priority<select value={draft.priority ?? ""} onChange={(event) => setDraft({ ...draft, priority: event.target.value === "" ? undefined : event.target.value as ITicketDraft["priority"] })} disabled={saving}><option value="">Not set</option>{TICKET_PRIORITIES.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label>Description<textarea value={draft.description ?? ""} onChange={(event) => setDraft({ ...draft, description: event.target.value || undefined })} disabled={saving} /></label><label>Assignee ID<input value={draft.assigneeId ?? ""} onChange={(event) => setDraft({ ...draft, assigneeId: event.target.value || undefined })} disabled={saving} /></label><button disabled={saving}>{saving ? "Saving…" : "Save ticket"}</button><button type="button" disabled={saving} onClick={onClose}>Cancel</button></form></dialog>;
}
